require 'rspec/core/rake_task'
require 'pact_broker/client/tasks'

$: << './lib'

RSpec::Core::RakeTask.new(:spec)

PactBroker::Client::PublicationTask.new do | task |
  require 'client/version'
  task.consumer_version = Client::VERSION
  task.pact_broker_base_url = 'http://localhost:3000'
  task.pact_broker_basic_auth = {username: 'broker', password: 'broker'}
end

task :default => :spec
